# Generated by Django 4.0.6 on 2022-08-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('full_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_department', to='assign.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('chairman_exp', models.BooleanField(default=False)),
                ('vice_chairman_exp', models.BooleanField(default=False)),
                ('secretary_exp', models.BooleanField(default=False)),
                ('committee_status', models.BooleanField(default=True)),
                ('review_count', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('student', models.CharField(max_length=100)),
                ('mssv', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topic_department', to='assign.department')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topic_group', to='assign.mygroup')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_mentor', to='assign.lecturer')),
                ('review_1', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='topic_review_first', to='assign.lecturer')),
                ('review_2', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='topic_review_second', to='assign.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopicToKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Hoàn toàn không'), (2, 'Ít'), (3, 'Bình thường'), (4, 'Nhiều'), (5, 'Hoàn toàn có')])),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_to_topic', to='assign.keyword')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_to_keyword', to='assign.topic')),
            ],
        ),
        migrations.CreateModel(
            name='MyCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='committee_group', to='assign.mygroup')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerToKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Hoàn toàn không'), (2, 'Ít'), (3, 'Bình thường'), (4, 'Nhiều'), (5, 'Hoàn toàn có')])),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_to_lecturer', to='assign.keyword')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_to_keyword', to='assign.lecturer')),
            ],
        ),
        migrations.AddField(
            model_name='lecturer',
            name='committee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_committee', to='assign.mycommittee'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.degree'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_department', to='assign.department'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='position',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_position', to='assign.position'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='work_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.workplace'),
        ),
    ]
