from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('grouping/', views.grouping, name="grouping"),
    path('change_test/', views.change_test, name="change_test"),
    path("lecturer-list/", views.LecturerList, name ="lecturer_list"),
    path("topic-list/", views.TopicList, name ="topic_list_not_approve"),
    path("topic-list-approved/", views.TopicListApproved, name ="topic_list_approved"),
    path("topic-approve/<int:pk>/", views.topic_approve, name="topic_approve"),
    path("topic-unapprove/", views.topic_unapprove, name="topic_unapprove"),
    path("lecturer-participate/", views.lecturer_participate, name="lecturer_participate"),
    path("lecturer-unparticipate/", views.lecturer_unparticipate, name="lecturer_unparticipate"),
    path('assign/', views.assign, name="assign"),
    path('change-assign-test/', views.change_assign_test, name="change_assign_test"),
    path('cannt-assign/', views.can_not_assign, name="cannt-assign"),
    path('topic-department-form/', views.topic_department_form, name="topic_department_form"),
    path('topic-form/', views.topic_form, name="topic_form"),
    path('topic-update-form/<int:pk>/', views.topic_update_form, name="topic_update_form"),
    path('topic-update/<int:pk>/', views.topic_update, name="topic_update"),
    path('lecturer-department-form/', views.lecturer_department_form, name="lecturer_department_form"),
    path('create-topic/', views.create_topic, name="create_topic"),
    path('lecturer-form/', views.lecturer_form, name="lecturer_form"),
    path('create-lecturer/', views.create_lecturer, name="create_lecturer"),
    path('review-assign/', views.review_assign, name="review_assign"),
    path('review-assign-form/', views.review_assign_form, name="review_assign_form"),
    path('assign_choose/', views.assign_choose, name="assign_choose"),
    path('keyword-form/', views.keyword_form, name="keyword_form"),
    path('keyword-create/', views.keyword_create, name="keyword_create"),
    path('export-xlsx-test/', views.export_committee_xlsx, name="export_committee_xlsx"),
    path('lecturer-update-form/', views.lecturer_update_form, name="lecturer_update_form"),
    path('lecturer-update/', views.lecturer_update, name="lecturer_update"),
    path("accounts/", include("django.contrib.auth.urls")),
]
